export {default as HomeIcon} from "./homeIcon"
export {default as UsersIcon} from "./usersIcon"
export {default as ReportIcon} from "./reportIcon"
export {default as UserIcon} from "./userIcon"
export {default as MeetingIcon} from "./meetingIcon"
export {default as EyeIcon} from "./eyeIcon"